### ISSUE TITLE
Error in Alan Studio: resolve() - globalContext can't be resolved

### ISSUE THREAD

**Issue by ljudbane** [alan-ai/alan-sdk-ionic#52]
We have noticed that from today (21.4.), clearing context programaticaly no longer works. And an error message is displayed in Alan Studio - `resolve() - globalContext can't be resolved`. 

The code that we use is:
```
projectAPI.greetUser = async function(p, param, callback) {
    p.play('Would you like me to give you a short overview of this month\'s statistics for your site?');
    
    const answer = await p.then(getYesNo);
    
    if (answer === 'yes') {
        playStatistics(p);
    } else if (answer === 'no') {
        p.play('OK, never mind then.');
    } else {
        // Cancelled context.
    }

    callback(null, 'ok');
};


// Context that locks user into yes/no answer.
const getYesNo = context(() => {
    title('Statistics overview');
    
    intent('(yes|sure|please|yes please|ok)', p => p.resolve('yes'));
    intent('(no|nope|never|cancel)', p => p.resolve('no'));
    fallback('Please say yes or no if you would like to hear a short overview of statistics.');
});

projectAPI.clearContextGlobal = function(p, param, callback) {
    try {
        p.resolve('cancel'); // Cancel yes/no context if it was active.
    } catch (e) {}
    callback(null, 'ok');
}
```

From mobile app we call `greetUser` function which locks user into a yes/no context. But if user performes some action in app, we must start another Alan dialog, so we call `clearContextGlobal` function, to close the yes/no context.

This used to work in the past, but no longer. Now the context stays active. Has there been any change in the way contexts work? I've read through the documentation on contexts, but i can't find if anything must be done differently.

The error message in Alan studio (`resolve() - globalContext can't be resolved`) happens at the same time as we call `clearContextGlobal` function from mobile app, so i presume it's connected.

**Comment by aermilin** [comment]
Hello, in this code you are trying to resolve the Global context, which is not allowed. Previously it was "working" due to a bug that has been fixed today. Documentation on your case should be updated by now.

If you want to resolve all active contexts (reset the dialog to just Global context) - you can use the new predefined function resetContext() (https://alan.app/docs/server-api/api/api-reference/#resetcontext). Which can be used anywhere in the script or directly right before you activate some context (https://alan.app/docs/server-api/contexts/#resetting-contexts).

When you need to resolve only one specific context (or resolve a context with some result i.e. "terminated" etc.) - you will save a "pointer" to this context using onEnter and then resolve it using this pointer. For your script it will look like this:

```
projectAPI.greetUser = async function(p, param, callback) {
    p.play('Would you like me to give you a short overview of this month\'s statistics for your site?');
    
    const answer = await p.then(getYesNo);
    
    if (answer === 'yes') {
        playStatistics(p);
    } else if (answer === 'no') {
        p.play('OK, never mind then.');
    } else {
        // Cancelled context.
    }

    callback(null, 'ok');
};


// Context that locks user into yes/no answer.
const getYesNo = context(() => {
    onEnter(p => {
        p.userData.ctxYesNo = p;
    });
    title('Statistics overview');
    
    intent('(yes|sure|please|yes please|ok)', p => p.resolve('yes'));
    intent('(no|nope|never|cancel)', p => p.resolve('no'));
    fallback('Please say yes or no if you would like to hear a short overview of statistics.');
});

projectAPI.clearContextGlobal = function(p, param, callback) {
    if (p.userData.ctxYesNo) {
        p.userData.ctxYesNo.resolve('cancel');
    }
}
```

**Comment by ljudbane** [comment]
Thank you for the detailed explanation. We've switched to using `resetContext()` function and it works as expected and it handles our use case.
